### ISSUE TITLE
Security Key option being selected but not clicking Next automatically.

### ISSUE THREAD

**Issue by DBRomano84** [Aldaviva/AuthenticatorChooser#6]
When I run this its working as it chooses the USB Security Key option but does not click next...anything I can provide to figure out why?  Win 11 23H2 ent 22631.4037

**Comment by Aldaviva** [comment]
Hi @DBRomano84,

Thank you for reporting this. Here are some possible causes:
1. One of your <kbd>Shift</kbd> keys is stuck down
    - This feature is there to let you do a one-time override of this program
    - Can be ruled out using your favorite text editor or [Keyboard Test Utility](https://www.softpedia.com/get/System/System-Info/Keyboard-Test-Utility.shtml)
1. There is a third option in the authenticator list, like a paired phone
    - This feature is there because of the increased likelihood of you wanting to use a paired phone if you already have one, although it's subjective
    - If you want to unpair a phone from FIDO, you can [edit the registry](https://github.com/Aldaviva/AuthenticatorChooser/wiki/Unpairing-Bluetooth-smartphone)
1. The Windows system locale does not match your Windows user's locale
    - This program follows the localization of your Windows user, but this dialog box is localized in a bizarre way
    - You can check the OS and user settings in Settings › Time & Language › Language & Region › Administrative Language Settings › Copy settings, where the Current User Display Language should equal the Welcome Screen Display Language
1. There is a defect in this program when finding or clicking the Next button
    - You should have seen an Uncaught Exception error message if this were the cause

I can also build a development snapshot of this program that has debugging messages so we can see why it's not able to click the Next button.

**Comment by DBRomano84** [comment]
> Hi @DBRomano84,
> 
> Thank you for reporting this. Here are some possible causes:
> 
> 1. One of your Shift keys is stuck down
>    
>    * This feature is there to let you do a one-time override of this program
>    * Can be ruled out using your favorite text editor or [Keyboard Test Utility](https://www.softpedia.com/get/System/System-Info/Keyboard-Test-Utility.shtml)
> 2. There is a third option in the authenticator list, like a paired phone
>    
>    * This feature is there because of the increased likelihood of you wanting to use a paired phone if you already have one, although it's subjective
>    * If you want to unpair a phone from FIDO, you can [edit the registry](https://github.com/Aldaviva/AuthenticatorChooser/wiki/Unpairing-Bluetooth-smartphone)
> 3. The Windows system locale does not match your Windows user's locale
>    
>    * This program follows the localization of your Windows user, but this dialog box is localized in a bizarre way
>    * You can check the OS and user settings in Settings › Time & Language › Language & Region › Administrative Language Settings › Copy settings, where the Current User Display Language should equal the Welcome Screen Display Language
> 4. There is a defect in this program when finding or clicking the Next button
>    
>    * You should have seen an Uncaught Exception error message if this were the cause
> 
> I can also build a development snapshot of this program that has debugging messages so we can see why it's not able to click the Next button.

Its option 2...I did a test of using an Android passkey via authenticator...I will remove that via reg as provided instructions.  Thank you.

**Comment by Aldaviva** [comment]
Great! Glad we got it figured out. It's very annoying that there's no easy way in any Windows UI to remove an existing phone from that dialog box.
